xlwings/xlwings

setup.py

This tiny modification should make it easier for linux users to figure out why the installation fails.
```
Processing /Users/ch/repo/xlwings
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/var/folders/x7/gzk1nby55r39gjz5y4gbl3lr0000gn/T/pip-CpB0u6-build/setup.py", line 23, in <module>
raise OSError("currently only Windows and OSX are supported.")
OSError: currently only Windows and OSX are supported.
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/var/folders/x7/gzk1nby55r39gjz5y4gbl3lr0000gn/T/pip-CpB0u6-build/setup.py", line 23, in <module>
raise OSError("currently only Windows and OSX are supported.")
15 if sys.platform.startswith('win'):
OSError: currently only …
```

setup.py: raise error when OS not supported.

---

xlwings/xlwings.bas

Modified ShowError to use Wscript.Shell.Popup in place of MsgBox
Changed line endings to vbCrLf for proper copy/paste from error popup.
Before:
After:
Reference: http://blogs.technet.com/b/heyscriptingguy/archive/2005/06/02/how-can-i-display-more-than-1-023-characters-in-a-custom-message-box.aspx

Allow for error messages longer than 1024 characters

---

setup.py
xlwings/_xlmac.py
xlwings/_xlwindows.py
xlwings/main.py
xlwings/tests/test_xlwings.py
xlwings/utils.py

This finally allows us to work reliably across different instances and correctly recognizes if a file is open even if it is from an untrusted location that would not be registered in the ROT.

Replaced GetObject/GetActiveObject/RunningObjectTable approach with HWND

---

xlwings/main.py

Throws an exception when a user tries to reference cell as if it was base 0, in response to bug #106.

Added exception when referencing (0,0); resolves #106

---

xlwings/_xlmac.py
xlwings/_xlwindows.py
xlwings/main.py
xlwings/tests/test_xlwings.py

Add left and top properties for Range, which return their locations on the worksheet in points. 
Should make this easier:
http://stackoverflow.com/questions/33725112/how-to-place-a-chart-with-xlwings-at-a-particular-worksheet-range-address-from-p

Add left and top properties for Range

---

xlwings/udfs.py
xlwings/xlwings.bas

Expand the variables in the xlwings.bas config paths.
Use python for PYTHONPATH and UDF_PATH, use the windows shell for the logfile on windows.
This also fixes the slashes in some paths as well, with seeming no bad effects.
Has only been tested on windows and python 2.7.11

Expand environmental vars

---

xlwings/_xlwindows.py

I found a side effect of the `_xlwindows.save_workbook` method. By turning `Application.DisplayAlerts` to False then True in this method it doesn't take into account the fact that this property can be False before the method is called.
This commit alters this behaviour so that the state of the `Application.DisplayAlerts` property is preserved. It allows a user to explicitly override this setting in their implementation.

preserve Application.DisplayAlerts 

---

xlwings/conversion/framework.py

I needed to access the ConversionContext in a converter of mine.
I may be wrong but it seems the current architecture only gives the ConversionContext.value to the converter.
I chose to overload the ToValueStage class in my converter this way : 
```
class ToValueStage(object):
def __init__(self, write_value, options):
self.write_value = write_value
self.options = options
def __call__(self, c):
self.options['range'] = c.range
c.value = self.write_value(c.value, self.options)
```
and consequently I had to change slighty the Converter class to make it work.

Modification of the converter class so it is possible to overload the ToValueStage and FromValueStage

---

xlwings/server.py

Syntax was not the right one, leading to parameters not being displayed as replacement of %s occurrences.
"exception" was written "exeception"

Display exception message parameters

---

xlwings/udfs.py

Add the ability to avoid calling an UDF when the Excel Function wizard (allowing to specify arguments) is opened.
This is particularly useful when an UDF does not return instantly.
Use `writeln` method instead of `write` to ease code understanding.

Avoid calling UDF with wizard

---

xlwings/server.py
xlwings/udfs.py

Retry COM call in case RPC_E_SERVERCALL_RETRYLATER error is returned (arbitrary set maximum number of retry to 9, total number of trial being 10 then)
For more information refer to https://msdn.microsoft.com/en-us/library/ms228772(v=vs.100).aspx?f=255&MSPPError=-2147217396
I am not fond of the fact that the number of retry is hardcoded here so if you find a way of providing options to xlwings properly it would be nice to introduce a property I guess.
Also please note that 10 might be a number a bit too high, in my case, most of the time 2 or 3 attempts were enough.

Retry COM call in case retry error is returned

---

xlwings/server.py

The syntax was not the right one (tested on Python 2.7 and 3.6):
```
>>> print('%s %s' % ('hello', 'world'))
hello world
>>> print('%s %s' % 'hello', 'world')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: not enough arguments for format string
```

Display error details in case of exception

---

docs/quickstart.rst

Just a small typo in the [quickstart page](http://docs.xlwings.org/en/stable/quickstart.html).
`import xlwings as xw` instead of `import xlwings xw`

[docs] Fix a small typo

---

docs/udfs.rst

Just a tiny typo in the [UDFs page](http://docs.xlwings.org/en/stable/udfs.html):
Lack of a colon after the function definition.

[docs] Fix a tiny typo in UDFs page

---

xlwings/__init__.py

Currently, if you have a file that contains UDFs destined for windows, with a decorator like: `@xw.arg('foo', doc='bar')`, this would generate an error on a non-windows platform:
```TypeError: arg() got an unexpected keyword argument 'doc'```

Enable cross-platform development of UDFs

---

docs/addin.rst
docs/whatsnew.rst
xlwings/addin/Config.bas

Current config system is:
- values in xlwings.conf sheet can override ...
- ... values from the user's ~/xlwings.conf file
The code in the PR modifies the config system:
- values in xlwings.conf sheet can override...
- ... values from xlwings.conf file in the workbook's folder can override ...
- ... values from the user's ~/xlwings.conf file
I have a scenario where a xlwings-powered workbook should be deployed to a Citrix environment. This change makes it easier to deploy a package w/ the workbook on the environment. With this change, the automated deployment system can simply create a text file in the workbook's directory.
(contrast without the change: Either make sure all users have ~/xlwings.conf file in their home directories, or use COM automation to modify contents of the workbook's …

Read config from (optional) xlwings.conf in workbook's directory

---

xlwings/conversion/standard.py

RawValueAccessor is not providing the options argument to the WriteValueToRangeStage constructor.

WriteValueToRangeStage construction error

---

xlwings/__init__.py

When working in windows environment, the `@xw.func` decorator for UDFs [preserves the docstring](https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/udfs.py#L119).
In non windows environment, since UDFs are not supported, the decorator is replaced by a [dummy function](https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/__init__.py#L38).
However, the docstring may still be useful for generating automated documentation, for instance with [Sphinx](http://www.sphinx-doc.org/en/master/)'s `.. automodule::` directive.

Preserve docstring of UDFs in non windows environments

---

xlwings/server.py

replaces #933
* fix typo
* decrease log level for retry
* use print if no handler is configured so it shows up in the console when setting the interpreter to `python` instead of `pythonw`

add logger

---

xlwings/server.py
xlwings/udfs.py

As mentioned in issue  #880   xlwings drops a delayed write (used for implementing dynamic UDFs) after 10 retries (a retry happens when call to Excel returns RPC_E_SERVERCALL_RETRYLATER). 
This PR removes limit on the number of retries while at the same not clogging the system. It is implemented by retrying periodically (at least every 100 ms) or earlier (when another task arrives).
The comments of issues #880 discuss the difference with PR #872 .

make retrying tasks more robust

---

xlwings/main.py
xlwings/tests/test_book.py
xlwings/tests/test_shape.py
xlwings/utils.py

This pull request adds support for [path-like objects](https://www.python.org/dev/peps/pep-0519/) (available in python 3.6 and higher) to API input arguments. It should now be possible for users to provide any object that is an instance of [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike) (which includes [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html) objects) as path argument.
The changes made basically amount to ensuring that any path-like object is converted to a string object at the earliest opportunity.
Included as well are some new unit tests with `pathlib.Path` objects.
Closes: #1124

Add support for path-like objects in API

---

xlwings/ext/sql.py

This is to fix a bug that shows up when the excel cell has both (") and (')
example: if cell contains the following text: X"Y'Z then sql.py will try to execute an INSERT statement with X"Y\'Z which is not understood by sqlite3 and causes an error. 
By replacing every \' instant by '' the statement error will be solved

Bug Fix: conflict on how python and sqlite3 interpret the apostrophe

---

xlwings/udfs.py

Bug: varargs does not work in combination with a "vba=" statement, for example to get the "Application" datastructure from excel.
Example:
@xw.arg('xl_app', vba='Application')
def vararg_func(xl_app, name, *args):
pass
Fix:
Changed the Python code that generates the vba function wrappers.
Just setting all "argsArray" elements separately did not work for datastructures like "Application".
Workaround: Build an Array(...) first, then Redim into desired size and fill with varargs.
Convention: varargs "*args" must be last in enumeration of arguments in Python!

Fixing bug of not being able to use vba=application and *args

---

xlwings/_xlwindows.py

Currently, running the following leaves a zombie process:
```
>>> app = xw.App()
>>> app.quit()
```
This is only cleaned up after properly quitting the python process, leaving it around hanging forever if e.g. the command prompt is closed directly.

Prevent zombie processes after running app.quit()

---

xlwings/udfs.py

So far, the easiest way to get to the caller object in the form of an xlwings range object was along these lines:
```python
import xlwings as xw
from xlwings import xlplatform
@xw.func
@xw.arg('xl', vba='Application')
def get_caller_address(xl):
return xw.Range(impl=xlplatform.Range(xl=xl.Caller)).address
```
This can now be done by introducing the `caller` argument:
```python
import xlwings as xw
@xw.func
def get_caller_address(caller):
return caller.address
```
On the Excel side, argument with the name `caller` will be hidden, so this function will have 0 arguments. That's a breaking change, but should have minimal impact as I don't expect many users to have an existing argument called `caller`. In any case, it's easily fixable by renaming existing arguments into something else.

introduced "caller" argument for UDFs

---

docs/installation.rst
docs/license.rst
setup.py
tests/conda_yml/win/xw26.yml
tests/conda_yml/win/xw27.yml
tests/conda_yml/win/xw33.yml
tests/conda_yml/win/xw34-pd-0.15.2.yml
tests/conda_yml/win/xw34.yml
tests/conda_yml/win/xw35-no-opt-deps.yml
tests/conda_yml/win/xw35.yml
xlwings/_xlwindows.py

Fixes #1443
What's missing:
- A news item for `docs/whatsnew.rst` because I'm not sure how you handle in-development items.
- I didn't touch the `docs/locales/**/*.po` files that popped up with `git grep --files-with-matches comtypes` because they look old and I don't know how to use them anyway.
- I haven't added or changed any tests because what's to test?
- I haven't run the tests because I'm on my mac today and I'm hoping your CI will just do it.

Remove comtypes requirement

---

xlwings/pro/reports/main.py

fixed a bug that was happening with the reports package in case you were using pictures without having pillow installed

reports: bug fix if pillow isn't available

---

docs/command_line.rst
xlwings/cli.py

This functionality allows you to easily write VBA code
in an external editor: run "xlwings vba edit" to
update the VBA modules of the active workbook from
their local exports everytime you hit save. If you run
this the first time, the modules will be automatically
exported from Excel. To overwrite the local version of
the modules with the one from Excel, run "xlwings vba
export". The "--file" flag allows you to specify a
file path instead of using the active Workbook.
Requires "Trust access to the VBA project object
model" enabled. WARNING: Don't use this tool if you're
actively changing the UserForm Layout as it currently
syncs back the exported state, which would overwrite any
changes that you made in Excel.

added new vba CLI command

---

MANIFEST.in
docs/command_line.rst
scripts/build_excel_files.py
setup.py
xlwings/cli.py

* Removes `xlwings addin install --unprotected`
* Will keep the package small since the addin will become bigger with the remote interpreter support
* Can still be done by manually going into the addin and removing the password protection

Remove addin_unprotected

---

docs/reports.rst
docs/whatsnew.rst

There are small typos in:
- docs/reports.rst
- docs/whatsnew.rst
Fixes:
- Should read `initial` rather than `intial`.
- Should read `anchor` rather than `achor`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

xlwings/cli.py

* install and remove add-in while Excel is running
* removed confusing `There is already an existing ~/.xlwings/xlwings.conf file`
* added `--dir` option to `addin remove` command

Allow add-in installation/removal while Excel is running

---

xlwingsjs/src/xlwings.ts

This fixes a broken `xlwings.min.js` (regression with 0.30.3)

Remove registerCallback to prevent webpack's treeshaking

---

.github/workflows/main.yml

Otherwise cryptography, a dependency of msal, shows a warning.

Switch CLI build back to 64bit [build-cli]

---

pyproject.toml
setup.py

As the developguide of xlwings states, xlwings is in transition to pytest. Therefor installing it with the 
```shell
pip install -e ".[all]"
```
command should also install pytest.

pytest as dependency for development

---

xlwings/_xlwindows.py

```python
import xlwings as xw
```
Package an exe application through `pyinstaller -w main.py` ,  main.py with the above code,  because the subprocess `tasklist` command is called, a black cmdline window will flash every time when the program exits.

Avoid the packaged application flashing black cmdline window.

---

tests/test_app.py

If I understand it correctly, the test relied upon the fact that `app2` was added last by `class TestBase(unittest.TestCase):` and therefore should be active, correct?
So perhaps make it more explicit (as in [zen rule nr 2](https://peps.python.org/pep-0020/) 😉)? It helps pass the test in my case. 
Related to #2261

Make activation explicit

---

tests/test_active.py

Similar to #2262. The test implicitly assumed that the last created app should also be the activated one. 
Also because of the transition to pytest, the `import unittest` is removed. Is the 
```Python
if __name__ == "__main__":
unittest.main()
```
needed as I haven't seen it in `test_font.py` as this was mentioned as the example module transitioned to pytest.

activate app before testing if it's active

---

xlwings/pro/_xlofficejs.py
xlwings/pro/custom_functions_code.js
xlwings/pro/udfs_officejs.py

* globalThis.getAuth and globalThis.socket are no longer required to be set in taskpane.html if unused
* custom function handle missing locals more gracefully with a warning instead of an error

Server fixes: removed required globalThis vars in JS and custom functions date format improvements

---

xlwings/pro/utils.py

This reverts commit b1e0c6843afb3c01d6a9bf2230708d93af471ca2.
```
from packaging.version import Version
```
requires Python 3.10+, but we have already `xlwings.utils.VersionNumber` that we can use.
Anyhow, instead of providing the version argument, it's easier to allow for deploy keys to be valid for any version <= the deploy key version.

Revert "allow to specify the xlwings version for the deploy key"

---

xlwings/__init__.py

Closes https://github.com/xlwings/xlwings-server/issues/231

Offer server decorators as top-level imports if pywin32 isn't installed

---

pyproject.toml
setup.py

Closes #2580
Simply adds a new optional dependency to pyproject.toml of the watchgod library enablings the usage of `xlwings vba edit` via uv:
uvx --from 'xlwings[vba_edit]' xlwings vba edit"
To test (before it gets merged) use the following:
`uvx --from "git+https://github.com/MEMAndersen/xlwings.git@2580-Add-optional-dependency-of-watchgod[vba_edit]" xlwings vba edit`
See also https://docs.astral.sh/uv/guides/tools/#requesting-extras
When #1963 is adressed the optional dependency should be updated
It is my first time contributing to anything so please guide or correct me if i am doing something wrong

2580 add optional dependency of watchgod

---

xlwings/pro/_xlremote.py
xlwings/pro/udfs_officejs.py

- xlwings Server always serves the correct version anyways as the frontend code is now part of xlwings-server (except if there are caching issues).
- xlwings Lite requires flexibility to be able to choose the xlwings version freely. Meaning that xlwings.js should be downward compatiable down to a minimimally required version, which shouldn't be any issue.

don't do version check with office.js
