xlwings/xlwings

- docs/quickstart.rst
> Updates example code with int(); resolves #167

- xlwings/xlwings.bas
Fix for https://github.com/ZoomerAnalytics/xlwings/issues/205
> Allow lowercase drive letters for PYTHON_WIN

- xlwings/xlwings.bas
Add quotes around PYTHON_WIN (necessary if blanks/spaces in path)
Change sys.path adaptation to handle multiple folder in PYTHONPATH.
If OK, it remains to update all xlsm files (template+examples). Is there a tool that does that automatically ?
> VBA module bugfix/enhancements (issues #258 and  #257)

- xlwings/main.py
- xlwings/tests/test_xlwings.py
Felix, I put the fix of issue #262 in a separate PR.
I have adapted the test suite but could not run it as I get a 
Traceback (most recent call last):
File "...\JetBrains\PyCharm 3.4\helpers\pycharm\utrunner.py", line 128, in <module>
all.addTests(testLoader.loadTestsFromTestCase(getattr(module, a[1])))
File "...\xlwings-dev\lib\unittest\loader.py", line 56, in loadTestsFromTestCase
loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
TypeError: this constructor takes no arguments
Any hint on how to run the test suite ?
> resize function + improve doc + fix tests (fix issue #262)

- xlwings/main.py
- xlwings/tests/test_xlwings.py
I have also added a test on this functionnality
> Fix issue in Sheet.add related to use of wkb keyword

- build_addins.py
I have no clue how to do it on Mac ...
> script to create xla and xlam addins

- xlwings/server.py
- xlwings/xlwings.bas
Only issue currently is that I didn't find a way to kill the server from a standard command prompt...Ctrl-C etc didn't seem to have an effect. It's easily killable in PyCharm though.
> Added UDF debug server

- xlwings/conversion/pandas_conv.py
On a mildy large range (4 columns x 70000 rows), this reduces by more than 60% the time to read a dataframe.
> performance improvement by avoiding intermediate object array

- experiment.py
- xlwings/conversion/__init__.py
- xlwings/conversion/framework.py
- xlwings/conversion/standard.py
got rid of writes_types
turned base_type into base
no need to implement router for standard case
> Simplified/Fixed Accessor/Converter API

- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
- xlwings/tests/test_xlwings.py
> added Range.formula_array

- docs/udfs.rst
Range should not be passed as string.
> typo in UDF tutorial

- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
- xlwings/tests/test_app.py
- xlwings/tests/test_book.py
- xlwings/tests/test_sheet.py
And some other minor changes/fixes
> Bluesky active refactor

- xlwings/udfs.py
Also avoid iteration on arguments in case excel version is < 14 (2010).
Also iterate only once over arguments in case excel version is >= 14 (2010).
I am also quite surprised that it was not working before but it fix the issue with my setup, I guess COM call should be completed with all arguments.
Description for each argument can be found on MSDN: https://msdn.microsoft.com/en-us/library/office/ff838997%28v=office.15%29.aspx?f=255&MSPPError=-2147217396
> UDF arguments documentation is now available

- xlwings/conversion/pandas_conv.py
nose tests ran fine on both pandas 0.20.3 and 0.21.1
> pandas.Index for single header, addesses #786

- xlwings/_xlwindows.py
> fixed COM retry wrapper when clicking in cells closes #587

- xlwings/_xlwindows.py
closes #759 as long as no COM objects are passed around.
> use pythoncom CoInitialize() so that you can use threading

- scripts/build_excel_files.py
> fixed standalone build (compiler constant was in wrong place)

- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
> Xlwings 1189 books open params

- src/xlwingsdll/config.cpp
> increased com server timeout to 1200

- xlwings/command_line.py
> print xlwings version with cli

- docs/locales/ja/LC_MESSAGES/installation.po
HI. I would like to translate xlwings documentation in japanese. First I translated "Installation" in Japanese. I hope you would approve my pull request, I’d be happy to continue translating other chapters in Japanese.
> translation "Instalation" in Japanese

- docs/locales/ja/LC_MESSAGES/installation.po
Remaining part of Instalation.
> Update installation.po Japanse translation

- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
- xlwings/tests/test_range.py
> Xlwings 80 insert row col

- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
- xlwings/tests/test_range.py
> range.delete

- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
- xlwings/tests/test_range.py
> range.copy

- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
- xlwings/tests/test_range.py
> range.paste

- docs/locales/ja/LC_MESSAGES/connect_to_workbook.po
- docs/locales/ja/LC_MESSAGES/datastructures.po
- docs/locales/ja/LC_MESSAGES/quickstart.po
- docs/locales/ja/LC_MESSAGES/syntax_overview.po
I've translated files below.
quickstart.rst
connect_to_workbook.rst
syntax_overview.rst
datastractures.rst
> Document translation of Japanese (quickstart.rst , e.t.c.)

- docs/locales/ja/LC_MESSAGES/addin.po
- docs/locales/ja/LC_MESSAGES/installation.po
addin.rst
installation.rst (update)
> Document translation of Japanese (addin.rst, e.t.c. )

- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/tests/test_conversion.py
Fixes #1116, handle more nan types
> Handle all different possibilities for np.nan

- scripts/build_excel_files.py
- xlwings/cli.py
as that would lock out the xlwings license functionality if it is expired
> removed hard xlwings import in cli 

- docs/license.rst
> Fix simple typo: specfic -> specific

- docs/locales/ja/LC_MESSAGES/udfs.po
- docs/locales/ja/LC_MESSAGES/vba.po
> Document translation of Japanese (vba.rst, e.t.c. )

- tests/test_range.py
- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
- xlwings/udfs.py
> Handle Range.Formula2

- docs/locales/ja/LC_MESSAGES/converters.po
- docs/locales/ja/LC_MESSAGES/debugging.po
- docs/locales/ja/LC_MESSAGES/installation.po
debugging.rst
converters.rst
installation.rst (update)
> Document translation of Japanese (debugging.rst, e.t.c.)

- docs/locales/ja/LC_MESSAGES/command_line.po
- docs/locales/ja/LC_MESSAGES/deployment.po
- docs/locales/ja/LC_MESSAGES/troubleshooting.po
command_line.rst
troubleshooting.rst
deployment.rst
> Document translation of Japanese (command_line.rst, e.t.c.)

- .gitignore
- docs/addin.rst
- docs/installation.rst
- docs/pro.rst
- docs/whatsnew.rst
- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/cli.py
- xlwings/main.py
> Xlwings 704 addin installation

- docs/command_line.rst
- xlwings/__init__.py
- xlwings/cli.py
> autoconfigure user config

- docs/locales/ja/LC_MESSAGES/addin.po
- docs/locales/ja/LC_MESSAGES/command_line.po
- docs/locales/ja/LC_MESSAGES/installation.po
- docs/locales/ja/LC_MESSAGES/vba.po
updated japanese translation of docs
> docs translation (ja)

- docs/command_line.rst
- docs/deployment.rst
- xlwings/cli.py
> Xlwings 1380 cli embed code

- xlwings/_xlwindows.py
> Fix COMRetryObjectWrapper II

- xlwings/utils.py
this should really be customizable, see #665 and #519, but will still improve the situation for now
> improve the resolution of matplotlib pictures

- xlwings/__init__.py
- xlwings/udfs.py
> ensure the generation of gen_py

- docs/command_line.rst
- docs/converters.rst
- docs/datastructures.rst
- docs/deployment.rst
- docs/installation.rst
- docs/pro.rst
- docs/r_and_julia.rst
- docs/threading_and_multiprocessing.rst
- docs/udfs.rst
- docs/vba.rst
- docs/whatsnew.rst
This PR fixes grammatical errors.
> Fix grammatical errors

- tests/test_sheet.py
- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
> Xlwings 123 copy sheet

- xlwings/_xlmac.py
closes #618. the timeout when writing values has to be solved by chunking instead
> removed timeout when opening and saving books on macOS

- docs/converters.rst
- docs/datastructures.rst
- tests/test_chunking.py
- xlwings/conversion/standard.py
- xlwings/main.py
- xlwings/utils.py
> xlwings-77 chunking

- xlwings/main.py
> add the exclude_start_string arg to book.to_pdf

- xlwings/main.py
> made create_report accessible as app method

- docs/reports.rst
- xlwings/pro/reports/main.py
> reports: added format filter

- xlwings/pro/reports/filters.py
- xlwings/pro/reports/main.py
Call them according to their position and allow them to be called multiple times. Closes #1675
> reports: refactored filters

- xlwings/main.py
- xlwings/pro/reports/main.py
- xlwings/pro/tables.py
* properly clean up App on Windows when used as context manager
* fix a bug with non-string headers when calling table.update
* reports: fix a bug when positioning shapes
> Various Bug Fixes

- xlwings/main.py
- xlwings/pro/reports/main.py
> refactor screen_update/display_alerts with new context manager

- xlwings/main.py
> added 'show' argument to to_pdf to open the generated PDF automatically

- xlwings/pro/reports/main.py
> reports: preserve row heights with single frames

- xlwings/cli.py
> added the --dir flag for xlwings addin install (CLI)

- xlwings/conversion/pandas_conv.py
Now works with MultiIndex, Series and Columns of PeriodDtype. Refactors the Series.write converter.
Fixes PR #1705 and issue #1084.
> Fixing PR 1705 for all cases

- tests/test_range.py
- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
> Added Range.copy_picture(), Range.to_png() and Chart.to_png()

- docs/reports.rst
- xlwings/pro/reports/filters.py
- xlwings/pro/reports/main.py
closes closes #1780 and closes #1779
> Reports: enhance aggsmall filter and ignore ## sheet names for both rendering and pdf printing

- .github/workflows/main.yml
- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
- xlwings/utils.py
Fixes https://github.com/xlwings/xlwings/issues/1708 and fixes https://github.com/xlwings/xlwings/issues/1697
> PDF export for charts and ranges and PDF export quality

- xlwings/utils.py
(can be at least .com or .us)
closes #1810
> fix regex for one drive for business 

- docs/command_line.rst
- xlwings/cli.py
* Export VBA modules to cwd instead of next to Excel file
* Requires [Y/n] confirmation
* Added "xlwings vba import"
* No more meta data is exported for ThisWorkbook/Sheet modules
> "xlwings vba ..." refactor

- .github/workflows/main.yml
- scripts/build_excel_files.py
- setup.py
- xlwings/cli.py
> Publish wheel and fix platform-specific dependencies

- tests/test_json/test_json.py
- xlwings/expansion.py
- xlwings/pro/_xljson.py
> fix json engine if range is partly outside used range

- xlwings/js/xlwings.js
> request proper OAuth scope

- xlwings/utils.py
> improve Sharepoint file handling on windows via registry

- xlwings/pro/reports/main.py
> raise explicit error when jinja2 is missing when using xw reports

- xlwings/cli.py
> ignore warning when checking version string of 1-click installer

- xlwings/_win32patch.py
- xlwings/_xlwindows.py
> hack to fix the pywin32>301 zombie process issue, see #1789

- xlwings/_xlmac.py
(responsible for activating window and app.visible property)
Closes #1966
> make system events optional on macOS

- xlwings/_xlmac.py
- xlwings/_xlwindows.py
- xlwings/main.py
> reuse code from Range class for myapp.range

- xlwings/conversion/pandas_conv.py
> handle pandas.Timedelta

- tests/test_book.py
- tests/test_sheet.py
- xlwings/main.py
to avoid confusion with sheet.names & book.names
replaces #2043
> replaces sheets.names with book.sheet_names 

- docs/markdown.rst
- docs/reports.rst
- xlwings/__init__.py
- xlwings/pro/reports/__init__.py
- xlwings/reports.py
> flatten xw.pro.reports to xw.reports and replaced register_formatter with @formatter decorator

- Cargo.lock
- Cargo.toml
- src/lib.rs
See https://github.com/xlwings/xcalamine/issues/6
> update xcalamine with fix for wrong decimals in xls reader

- Cargo.lock
- Cargo.toml
- about.toml
- docs/_static/opensource_licenses2.html
- src/lib.rs
* Turn ints to floats to be in line with the interactive (COM/appscript) behavior
* Let pyo3 handle DateTime conversion (added with pyo3 0.17.2)
> Reader: turn ints to float and let pyo3 handle datetime

- xlwings/js/xlwings.js
presumably caused by a runtime change in toLocaleString
> Fix date parsing on Google Sheets 

- xlwings/pro/reports/main.py
> replace copy/paste format with autofill

- xlwings/_xlwindows.py
- xlwings/base_classes.py
- xlwings/main.py
called automatically with app.quit() and app.kill(). Closes #2001
> added apps.cleanup() to remove zombie processes

- xlwings/pro/reports/main.py
This fixes a regression introduced with 0.30.1
> reports: don't autofill tables in frames

- xlwings/__init__.py
- xlwings/main.py
> show more meaningful errors when there are engines missing

- tests/test_engines/test_engines.py
- xlwings/pro/_xlremote.py
Allow to do `mysheet["mytable"]`, which returns the data body range.
> Server: Allow to access tables via range

- Cargo.lock
- Cargo.toml
- docs/pro/reader.rst
- src/lib.rs
- tests/pandas_excel_files_quick_test.py
- tests/test_engines/test_engines.py
> Reader: Add datetime support for xls & xlsb

- .pre-commit-config.yaml
Updating the pre-commit versions to resolve #2273 for future developers.
> Update version pre-commit

- xlwings/udfs.py
essentially reverting https://github.com/xlwings/xlwings/pull/1318/commits/ad0c9220afcac64cff3dfc51d438f7a680c19852
> upgraded asyncio since 3.6/3.7 support has been dropped

- docs/command_line.rst
- docs/whatsnew.rst
- xlwings/cli.py
This was originally thought as a joke in reply to the below tweet, but as long as Python in Excel doesn't offer a proper editor, it turns out to be actually quite useful!
> Added `xlwings py edit` CLI command

- xlwings/cli.py
> added explicit encoding when reading text files

- xlwings/utils.py
> fix sharepoint regression

- docs/pro/server/officejs_addins.rst
- xlwings/html/xlwings-alert.html
- xlwingsjs/devserver.py
- xlwingsjs/src/alert.ts
- xlwingsjs/src/auth.ts
- xlwingsjs/src/utils.ts
- xlwingsjs/src/xlwings.ts
* await Office.onReady() in the js functions
* handle prompt line breaks in template (xlwings-alert.html)
> xlwings.js enhancements

- xlwings/base_classes.py
- xlwings/main.py
- xlwings/pro/_xlremote.py
- xlwingsjs/src/xlwings.ts
> implement Range.adjust_indent for Office.js

- xlwings/utils.py
> fix utcfromteimstamp deprecation

- xlwings/pro/custom_functions_code.js
for now with semaphore and retries
> cope with many concurrent custom function calls

- xlwings/main.py
- xlwings/utils.py
* fixes undefined mound_point
* fixes add_workbook_to_path=False when PYTHONPATH to Python file is provided
> fix macOS onedrive/sharepoint issues, closes #2496

- xlwings/pro/custom_functions_code.js
> fix varargs for object handles

- docs/extensions.rst
- xlwings/ext/sql.py
> enhanced sql formula to optionally accept custom aliases instead of a,b,c

- xlwings/pro/_xlremote.py
Closes https://github.com/xlwings/xlwings-server/issues/234
> xlwings Server: fixed missing datetime conversion when writing pd.datetime to excel
